version: '3'

services:
  # ORDS service
  tomcat:
    container_name: apex_tomcat
    depends_on:
      - db
    image: dnraikes/tomcat9-ords:20.2
    volumes:
      - apex_tomcat:/u01/www
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - oracle_network
    restart: unless-stopped

  # Oracle Database service
  db:
    container_name: apex_db
    image: dnraikes/db193-apex:20.1
    volumes:
      - apex_db:/opt/oracle/oradata
    ports:
      - "1521:1521"
    networks:
      - oracle_network
    restart: unless-stopped

volumes:
    apex_db:
    apex_tomcat:

networks:
  oracle_network:
